name: Build, Release, and Upload Windows Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Windows Installer
      run: npm run build:win

    - name: Create Release
      id: create_release
      uses: actions/github-script@v6
      with:
        script: |
          const version = require('./package.json').version;
          const response = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `v${version}`,
            name: `Release v${version}`,
            draft: false,
            prerelease: false
          });
          echo $response.data.upload_url;
          return response.data.upload_url;
    
    - name: Upload Windows Installer
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/taskmatrix-*.exe
        asset_name: taskmatrix-setup.exe
        asset_content_type: application/octet-stream
